import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const api = window.firmwareAPI;

function GatewayPanel({ run }) {
  const [host,setHost]=useState(''),[token,setToken]=useState(''),[status,setStatus]=useState(null),[device,setDevice]=useState(null),[firmware,setFirmware]=useState(''),[confirm,setConfirm]=useState(false);
  const connect=()=>run(async()=>{setStatus(await api.gatewayStatus(host.trim(),token.trim()));setDevice(null)});
  const inspect=()=>run(async()=>setDevice(await api.gatewayInspect(host.trim(),token.trim())));
  const backup=()=>run(()=>api.gatewayBackup({host:host.trim(),token:token.trim(),baud:115200,size:'0x400000'}));
  const flash=()=>run(async()=>{await api.gatewayFlash({host:host.trim(),token:token.trim(),file:firmware,address:'0x0',baud:115200});setConfirm(false)});
  return <div className="grid gatewayGrid"><section className="card wide"><div className="cardTitle"><span>01</span><div><h3>Pair with phone gateway</h3><p>Enter the IP address and temporary token shown in the Android app.</p></div></div><div className="pairRow"><label>Phone IP<input placeholder="192.168.1.50" value={host} onChange={e=>setHost(e.target.value)}/></label><label>Pairing token<input placeholder="12-character token" value={token} onChange={e=>setToken(e.target.value.toUpperCase())}/></label><button className="primary" disabled={!host||token.length<8} onClick={connect}>Connect securely</button></div>{status&&<div className="success">Phone connected - {status.device?`USB VID:${status.device.vendorId.toString(16)} PID:${status.device.productId.toString(16)}`:'no ESP adapter attached'}</div>}</section><section className="card"><div className="cardTitle"><span>02</span><div><h3>Inspect through phone</h3><p>Route a read-only probe through the authenticated bridge.</p></div></div>{device?<div className="facts"><div><small>CHIP</small><b>{device.chip}</b></div><div><small>MAC</small><b>{device.mac}</b></div></div>:<div className="empty">No remote ESP identity read.</div>}<button className="primary" disabled={!status?.device} onClick={inspect}>Inspect remote ESP</button><button className="secondary" disabled={!device} onClick={backup}>Back up 4 MB flash</button></section><section className="card"><div className="cardTitle"><span>03</span><div><h3>Update through gateway</h3><p>Firmware stays on the desktop and is streamed through the phone.</p></div></div><div className="file"><span>{firmware||'No .bin selected'}</span><button onClick={async()=>setFirmware(await api.pickFirmware()||firmware)}>Browse</button></div><div className="warning">Use the exact board image. Some USB adapters require holding BOOT and tapping RESET.</div><label className="check"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> I verified the remote board, image, backup and recovery procedure.</label><button className="danger" disabled={!device||!firmware||!confirm} onClick={flash}>Flash through phone</button></section><section className="card wide"><div className="cardTitle"><span>ROUTER</span><div><h3>Router gateway mode</h3><p>Detection and secure control are available. Firmware writes remain locked until a model adapter validates the image and recovery method.</p></div></div></section></div>;
}

function App() {
  const [mode, setMode] = useState('esp'); const [busy, setBusy] = useState(false); const [log, setLog] = useState('Ready. Connect a device over USB.\n');
  const [ports, setPorts] = useState([]), [port, setPort] = useState(''), [esp, setEsp] = useState(null), [firmware, setFirmware] = useState(''), [confirm, setConfirm] = useState(false);
  const [phones, setPhones] = useState([]), [serial, setSerial] = useState(''), [phone, setPhone] = useState(null), [apk, setApk] = useState('');
  const [fastboot, setFastboot] = useState([]), [image, setImage] = useState(''), [partition, setPartition] = useState('boot'), [flashConfirm, setFlashConfirm] = useState(false);
  const [phoneLog, setPhoneLog] = useState(''), [logging, setLogging] = useState(false);
  const [detected, setDetected] = useState([]), [watching, setWatching] = useState(true);
  useEffect(() => api.onLog(x => setLog(v => (v + x).slice(-40000))), []);
  useEffect(() => api.onAndroidLog(x => setPhoneLog(v => (v + x).slice(-50000))), []);
  useEffect(() => {
    let alive = true;
    async function tick() {
      if (!watching || busy) return;
      try {
        const result = await api.watchDevices();
        if (!alive || result.busy) return;
        setDetected(result.devices);
        const serialDevices = result.devices.filter(d => d.protocol === 'Serial').map(d => ({ path: d.port, manufacturer: d.name }));
        const adbDevices = result.devices.filter(d => d.protocol === 'ADB').map(d => ({ serial: d.serial, model: d.name, state: d.detail }));
        const fastbootDevices = result.devices.filter(d => d.protocol === 'Fastboot').map(d => ({ serial: d.serial }));
        setPorts(serialDevices); setPhones(adbDevices); setFastboot(fastbootDevices);
        if (!port && serialDevices[0]) setPort(serialDevices[0].path);
        if (!serial && adbDevices[0]) setSerial(adbDevices[0].serial);
      } catch {}
    }
    tick(); const timer = setInterval(tick, 3000);
    return () => { alive = false; clearInterval(timer); };
  }, [watching, busy, port, serial]);
  async function run(fn) { setBusy(true); try { await fn(); } catch (e) { setLog(v => `${v}\nERROR: ${e.message}\n`); } finally { setBusy(false); } }
  async function scan() { if (mode === 'esp') return run(async()=>{const x=await api.listPorts();setPorts(x);if(x[0])setPort(x[0].path)}); return run(async()=>{const a=await api.androidList();setPhones(a);if(a[0])setSerial(a[0].serial);try{setFastboot(await api.fastbootList())}catch{setFastboot([])}}); }
  async function toggleLog() { await run(async()=>{if(logging)await api.androidStopLog();else{setPhoneLog('');await api.androidStartLog(serial)}setLogging(!logging)}); }
  if(mode==='gateway') return <div className="app"><aside><div className="brand"><div className="mark">FF</div><div><b>Firmware Forge</b><small>DEVICE WORKBENCH</small></div></div><nav><button onClick={()=>setMode('esp')}>ESP32 boards</button><button onClick={()=>setMode('android')}>Android phones</button><button className="active">Phone gateway</button><button>Firmware library</button><button>Activity</button></nav><div className="support"><span></span><div><b>Gateway adapter</b><small>Authenticated LAN + USB</small></div></div><div className="router"><b>Safety boundary</b><p>The phone authorizes every session. Unsupported routers and unknown hardware remain read-only.</p></div></aside><main><header><div><p className="eyebrow">REMOTE USB OPERATIONS</p><h1>Phone gateway</h1><p>Control an ESP32 attached to your phone over an authenticated local bridge.</p></div></header><GatewayPanel run={run}/><section className="card wide console operation"><div className="tabs"><b>Gateway operation log</b></div><pre>{log}</pre></section></main></div>;
  return <div className="app"><aside><div className="brand"><div className="mark">FF</div><div><b>Firmware Forge</b><small>DEVICE WORKBENCH</small></div></div><nav><button className={mode==='esp'?'active':''} onClick={()=>setMode('esp')}>ESP32 boards</button><button className={mode==='android'?'active':''} onClick={()=>setMode('android')}>Android phones</button><button className={mode==='gateway'?'active':''} onClick={()=>setMode('gateway')}>Phone gateway</button><button>Firmware library</button><button>Activity</button></nav><div className="support"><span></span><div><b>{mode==='gateway'?'Gateway adapter':mode==='esp'?'ESP32 adapter':'Android adapter'}</b><small>{mode==='gateway'?'Authenticated LAN + USB':mode==='esp'?'esptool':'ADB + Fastboot'}</small></div></div><div className="router"><b>Safety boundary</b><p>Bootloader locks, Verified Boot and vendor signatures are never bypassed.</p></div></aside>
  <main><header><div><p className="eyebrow">USB FIRMWARE OPERATIONS</p><h1>{mode==='gateway'?'Phone gateway':mode==='esp'?'ESP32 device lab':'Android device lab'}</h1><p>{mode==='gateway'?'Control an ESP32 attached to your phone over an authenticated local bridge.':mode==='esp'?'Inspect, back up and update development boards.':'Inspect and test with ADB; flash approved partitions with Fastboot.'}</p></div>{mode!=='gateway'&&<div className="headerActions"><button className={watching?'watchOn':'watchOff'} onClick={()=>setWatching(!watching)}>{watching?'Auto-detect on':'Auto-detect off'}</button><button className="scan" disabled={busy} onClick={scan}>Scan now</button></div>}</header>
  <section className="detector"><div className="detectorHead"><b>Connected hardware</b><span>{detected.length} detected</span></div><div className="deviceChips">{detected.length?detected.map(d=><button key={d.id} className={`deviceChip ${d.kind}`} onClick={()=>{if(d.kind==='android')setMode('android');if(d.kind==='esp-candidate'){setMode('esp');setPort(d.port)}}><i></i><span><b>{d.name}</b><small>{d.kind==='esp-candidate'?'Probable ESP serial adapter - inspect to confirm':d.kind==='router-candidate'?'Possible router - read only until model adapter exists':d.kind==='android'?`Android confirmed via ${d.protocol}`:d.detail}</small></span></button>):<p>No USB, ADB, Fastboot or serial devices detected.</p>}</div></section>
  {mode==='esp'?<><section className="hero"><div className="plug">USB</div><div><span className="status">{ports.length?'PORT FOUND':'WAITING FOR DEVICE'}</span><h2>{port||'Connect an ESP32 board'}</h2><p>Use a data-capable USB-C cable.</p></div><select value={port} onChange={e=>{setPort(e.target.value);setEsp(null)}}><option value="">Select port</option>{ports.map(p=><option key={p.path}>{p.path}</option>)}</select></section><div className="grid">
    <section className="card"><div className="cardTitle"><span>01</span><div><h3>Identify device</h3><p>Read chip identity before writing.</p></div></div>{esp?<div className="facts"><div><small>CHIP</small><b>{esp.chip}</b></div><div><small>MAC</small><b>{esp.mac}</b></div></div>:<div className="empty">No identity read.</div>}<button className="primary" disabled={!port||busy} onClick={()=>run(async()=>setEsp(await api.inspect(port,115200)))}>Inspect ESP</button></section>
    <section className="card"><div className="cardTitle"><span>02</span><div><h3>Back up flash</h3><p>Create a 4 MB recovery image.</p></div></div><button className="secondary" disabled={!esp||busy} onClick={()=>run(()=>api.backup({port,baud:460800,size:'0x400000'}))}>Create backup</button></section>
    <section className="card wide"><div className="cardTitle"><span>03</span><div><h3>Flash firmware</h3><p>Write and verify a binary at offset 0x0.</p></div></div><div className="file"><span>{firmware||'No .bin selected'}</span><button onClick={async()=>setFirmware(await api.pickFirmware()||firmware)}>Browse</button></div><div className="warning">The wrong image can make the board unbootable.</div><label className="check"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> I verified the image, board and backup.</label><button className="danger" disabled={!esp||!firmware||!confirm||busy} onClick={()=>run(()=>api.flash({port,baud:460800,file:firmware,address:'0x0'}))}>Flash and verify</button></section></div></>:<>
    <section className="hero"><div className="plug">ADB</div><div><span className="status">{phones.length?'PHONE FOUND':fastboot.length?'FASTBOOT FOUND':'WAITING FOR PHONE'}</span><h2>{phones.find(x=>x.serial===serial)?.model||fastboot[0]?.serial||'Connect an Android phone'}</h2><p>Enable USB debugging and approve this computer on the phone.</p></div><select value={serial} onChange={e=>{setSerial(e.target.value);setPhone(null)}}><option value="">Select ADB device</option>{phones.map(x=><option key={x.serial} value={x.serial}>{x.model||x.serial} - {x.state}</option>)}</select></section><div className="grid">
    <section className="card wide"><div className="cardTitle"><span>01</span><div><h3>Inspect phone</h3><p>Read build and security information without modifying it.</p></div></div>{phone?<div className="androidFacts">{[['DEVICE',`${phone.manufacturer} ${phone.model}`],['ANDROID',`${phone.android} / SDK ${phone.sdk}`],['SECURITY PATCH',phone.securityPatch],['VERIFIED BOOT',phone.verifiedBoot],['BUILD',phone.build],['BATTERY',`${phone.battery}%`]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div>:<div className="empty">No phone inspected. Approve the USB debugging prompt first.</div>}<button className="primary" disabled={!serial||busy} onClick={()=>run(async()=>setPhone(await api.androidInspect(serial)))}>Inspect phone</button></section>
    <section className="card"><div className="cardTitle"><span>02</span><div><h3>Test and deploy</h3><p>Install an APK or enter a service mode.</p></div></div><div className="file"><span>{apk||'No APK selected'}</span><button onClick={async()=>setApk(await api.androidPickApk()||apk)}>Browse</button></div><button className="secondary" disabled={!phone||!apk||busy} onClick={()=>run(()=>api.androidInstallApk(serial,apk))}>Install / update APK</button><div className="buttonRow"><button className="secondary" disabled={!phone||busy} onClick={()=>run(()=>api.androidReboot(serial,'recovery'))}>Recovery</button><button className="secondary" disabled={!phone||busy} onClick={()=>run(()=>api.androidReboot(serial,'bootloader'))}>Bootloader</button></div></section>
    <section className="card"><div className="cardTitle"><span>03</span><div><h3>Fastboot firmware</h3><p>Flash one allowlisted partition.</p></div></div><label>Partition<select value={partition} onChange={e=>setPartition(e.target.value)}>{['boot','vendor_boot','recovery','system','vendor','product','dtbo','vbmeta'].map(x=><option key={x}>{x}</option>)}</select></label><div className="file"><span>{image||'No .img selected'}</span><button onClick={async()=>setImage(await api.fastbootPickImage()||image)}>Browse</button></div><div className="warning">Requires the exact OEM image and an unlocked bootloader. This can erase data or brick the phone.</div><label className="check"><input type="checkbox" checked={flashConfirm} onChange={e=>setFlashConfirm(e.target.checked)}/> I verified model, region, build, partition and recovery plan.</label><button className="danger" disabled={!fastboot.length||!image||!flashConfirm||busy} onClick={()=>run(()=>api.fastbootFlash({serial:fastboot[0].serial,partition,file:image}))}>Flash {partition}</button></section>
    <section className="card wide console"><div className="tabs"><b>Android logcat</b><button className={logging?'live':''} disabled={!serial||busy} onClick={toggleLog}>{logging?'Stop logcat':'Start logcat'}</button></div><pre>{phoneLog||'Start logcat to test applications and system behavior.'}</pre></section></div></>}
  <section className="card wide console operation"><div className="tabs"><b>Operation log</b></div><pre>{log}</pre></section></main></div>;
}
createRoot(document.getElementById('root')).render(<App />);
